#!/bin/bash
# This script get content to command pip freeze and execute them

PS3='> Quelles actions souhaitez-vous effectuer ? ' 
LIST=("[p] pip freeze" "[i] install" "[c] cancel")

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

select CHOICE in "${LIST[@]}" ; do
    case $REPLY in

        1|p)
            pip freeze > requirements.txt
            echo "${green}Les paquets ont été écrit dans requirements.txt !${reset}"
            break;;

        2|i)
            for element in $(cat requirements.txt);
                do
                    pip install ${element%%=*}
                done
            echo "${green}Installations des paquets terminés !${reset}"
            break;;
        
        3|c)
            echo "${red}Exit${reset}"
            break;;
    esac
done